version: "3.8"

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    volumes:
      - ./.docker/postgres-data:/var/lib/postgresql/data
    networks:
      fragment-protocol:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${DJANGO_PORT}:8000"
    depends_on:
      - db
      - rabbitmq
    networks:
      fragment-protocol:
    env_file: .env
  checker:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    networks:
      fragment-protocol:
    env_file: .env
    command: poetry run python checker.py
  receiver:
    build:
      context: .
      dockerfile: dockerfiles/receiver.Dockerfile
    depends_on:
      - db
      - rabbitmq
    restart: unless-stopped
    networks:
      fragment-protocol:
    env_file: .env
  rabbitmq:
    image: rabbitmq:3-management-alpine
    # container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER:
      RABBITMQ_DEFAULT_PASS:
      RABBITMQ_DEFAULT_VHOST:
    networks:
      fragment-protocol:

networks:
  fragment-protocol: