# Generated by Django 3.2 on 2021-04-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locked_nft', '0004_alter_bep20_tokenaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='bep20',
            name='decimals',
            field=models.IntegerField(max_length=64, null=True),
        ),
    ]
