# Generated by Django 3.2 on 2021-04-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LockedNFT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=50, unique=True)),
                ('nftAddress', models.CharField(max_length=50)),
                ('nftId', models.IntegerField()),
            ],
        ),
    ]
