# Generated by Django 3.2 on 2021-04-20 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locked_nft', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BEP20',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokenAddress', models.CharField(max_length=50, unique=True)),
                ('created_from', models.CharField(max_length=50)),
                ('current_balance', models.CharField(max_length=256)),
                ('total', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='lockednft',
            name='ready_to_withdraw',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lockednft',
            name='owner',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='lockednft',
            name='bep20',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bep20', to='locked_nft.bep20'),
        ),
    ]
