# Generated by Django 3.2 on 2021-04-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locked_nft', '0002_auto_20210420_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='lockednft',
            name='image_url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='lockednft',
            name='name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='lockednft',
            name='permalink',
            field=models.TextField(null=True),
        ),
    ]
