# Generated by Django 3.2 on 2021-04-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locked_nft', '0003_auto_20210420_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bep20',
            name='tokenAddress',
            field=models.CharField(max_length=50),
        ),
    ]
