# Generated by Django 3.2 on 2021-04-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locked_nft', '0005_bep20_decimals'),
    ]

    operations = [
        migrations.AddField(
            model_name='bep20',
            name='burned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bep20',
            name='decimals',
            field=models.IntegerField(null=True),
        ),
    ]
