# Generated by Django 3.2 on 2021-04-22 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locked_nft', '0006_auto_20210421_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lockednft',
            name='bep20',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nft', to='locked_nft.bep20'),
        ),
    ]
